package demo.mapper;

import demo.model.User;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Sep 10 17:41:53 PDT 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Sep 10 17:41:53 PDT 2015
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Sep 10 17:41:53 PDT 2015
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Sep 10 17:41:53 PDT 2015
	 */
	List<User> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Thu Sep 10 17:41:53 PDT 2015
	 */
	int updateByPrimaryKey(User record);

	/**
	 * 
	 * @param record
	 * @param bounds
	 * @return
	 */
	User[] selectList(User record, RowBounds bounds);
}